version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build:
      dockerfile: Dockerfile.local
    container_name: server
    command: gin run main.go
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      MONGODB_CONNECTION_STRING: mongodb://root:example@mongo:27017/
    volumes:
      - .:/app
